version: '3.7'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "8080:443"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
      - elasticsearch
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "ELASTICSEARCH_HOSTS=elasticsearch:9200"
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
      - composer:/root/.composer/cache
    depends_on:
      - mysql
      - redis
      - elasticsearch
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "COMPOSER_MEMORY_LIMIT=-1"
      - "ELASTICSEARCH_HOSTS=elasticsearch:9200"
    tty: true
  mysql:
    container_name: mysql
    build:
      context: ./
      dockerfile: docker/mysql.docker
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    ports:
      - "33061:3306"
  redis:
    image: redis:3.0
    volumes:
      - redis:/data
    ports:
      - "63791:6379"
  node:
    image: node:8.6-alpine
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./storage/docker/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"

volumes:
  composer:
  mysql:
  redis:
